INTERNAL_GW_MEMORY_LIMIT: "475Mi"
PRIVATE_GW_MEMORY_LIMIT: "150Mi"
PUBLIC_GW_MEMORY_LIMIT: "475Mi"
EGRESS_GW_MEMORY_LIMIT: "64Mi"
INTERNAL_GW_CPU_LIMIT: "2"
PRIVATE_GW_CPU_LIMIT: "500m"
PUBLIC_GW_CPU_LIMIT: "1"
EGRESS_GW_CPU_LIMIT: "100m"
CPU_REQUEST: "100m"
REPLICAS: 2
HPA_ENABLED: true
HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT: 75
HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS: 60
HPA_SCALING_UP_PODS_PERIOD_SECONDS: 60
HPA_SCALING_UP_PODS_VALUE: 1
HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS: 300
HPA_SCALING_DOWN_PODS_PERIOD_SECONDS: 60
HPA_SCALING_DOWN_PODS_VALUE: 1
HPA_MIN_REPLICAS: 2
HPA_MAX_REPLICAS: 5
HPA_SCALING_UP_SELECT_POLICY: Max
HPA_SCALING_DOWN_SELECT_POLICY: Max
HPA_SCALING_UP_PERCENT_PERIOD_SECONDS: -1
HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS: -1