---
kind: ConfigMap
apiVersion: v1
metadata:
    name: 'core-gateway-image'
    labels:
      app.kubernetes.io/part-of: 'Cloud-Core'
      app.kubernetes.io/managed-by: 'saasDeployer'
      deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
data:
    image: '{{ .Values.IMAGE_REPOSITORY }}:{{ .Values.TAG }}'
