name: Build on Commit

on:
  - push

jobs:
  docker-build:
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@68e865434b0548d4ad2192e368bc5e898a0ce2ed # v2.4.2
    with:
      dry-run: false
