name: Build on Commit

on:
  - push

jobs:
  docker-build:
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@9d3a0721f4cd8cdd9d762ac092c5c5d2d051cdea # v2.5.1
    with:
      dry-run: false
