name: Build on Commit

on:
  - push

jobs:
  docker-build:
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@afe90353c9a086f22355f99e14e24a06cfb5195b # v2.4.3
    with:
      dry-run: false
